
services:
    midata.schnittstelle:
        class: PfadiZytturm\MidataBundle\Service\pbsSchnittstelle
        autowire: true
        autoconfigure: true
        calls:
        - [setDatacollector, ['@?midata.collector']]

    PfadiZytturmMidataBundle\Controller\midataMailController:
        class: PfadiZytturm\MidataBundle\Controller\midataMailController
        autowire: true
        autoconfigure: true
        arguments: ["@service_container", "@midata.schnittstelle", "@security.token_storage"]

    PfadiZytturm\MidataBundle\Service\pbsSchnittstelle: '@midata.schnittstelle'

    midata.collector:
        class: PfadiZytturm\MidataBundle\DataCollector\midataDataCollector
        # PfadiZytturm\MidataBundle\DataCollector\midataDataCollector
        tags:
        - name:     data_collector
          template: '@PfadiZytturmMidata/datacollector.html.twig'
            # must match the value returned by the getName() method
          id:       'midata.collector'
            # optional priority
            # priority: 300

#    pfadi_zytturm_midata.example:
#        class: PfadiZytturm\MidataBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#services:
#    pfadi_zytturm_midata.schnittstelle:
#        class: PfadiZytturm\MidataBundle\src\pbsSchnittstelle
#        arguments:
#            $url: "%pfadi_zytturm_midata.midata.url%"
#            $user: "a"
#            $password: "a"
#            $groupId: "a"
#            $cacheTTL: "a"


#    pfadi_zytturm_midata.example:
#        class: PfadiZytturm\MidataBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
